#!/usr/bin/env sh

# Get staged files in src directory with specific extensions
FILES=$(git diff --cached --name-only --diff-filter=ACMR "src/*.ts" "src/*.tsx" "src/*.css" "src/*.json")

# Exit if no files are staged
if [ -z "$FILES" ]; then
    exit 0
fi

# Run biome on staged files
npx biome format $FILES
npx biome lint $FILES

# Add back the modified files to staging
git add $FILES